import type { CategoryName } from '../shared/types'
import { CATEGORY_COLORS } from '../shared/types'

// Maps exe name (lowercase) to friendly display name
const APP_NAME_MAP: Record<string, string> = {
  'code.exe': 'Visual Studio Code',
  'code - insiders.exe': 'VS Code Insiders',
  'devenv.exe': 'Visual Studio',
  'idea64.exe': 'IntelliJ IDEA',
  'pycharm64.exe': 'PyCharm',
  'webstorm64.exe': 'WebStorm',
  'phpstorm64.exe': 'PhpStorm',
  'rider64.exe': 'Rider',
  'clion64.exe': 'CLion',
  'goland64.exe': 'GoLand',
  'datagrip64.exe': 'DataGrip',
  'cursor.exe': 'Cursor',
  'sublime_text.exe': 'Sublime Text',
  'notepad++.exe': 'Notepad++',
  'atom.exe': 'Atom',
  'vim.exe': 'Vim',
  'nvim.exe': 'Neovim',
  'chrome.exe': 'Google Chrome',
  'firefox.exe': 'Firefox',
  'msedge.exe': 'Microsoft Edge',
  'opera.exe': 'Opera',
  'brave.exe': 'Brave',
  'vivaldi.exe': 'Vivaldi',
  'iexplore.exe': 'Internet Explorer',
  'slack.exe': 'Slack',
  'discord.exe': 'Discord',
  'teams.exe': 'Microsoft Teams',
  'zoom.exe': 'Zoom',
  'skype.exe': 'Skype',
  'telegram.exe': 'Telegram',
  'whatsapp.exe': 'WhatsApp',
  'signal.exe': 'Signal',
  'mattermost.exe': 'Mattermost',
  'outlook.exe': 'Microsoft Outlook',
  'thunderbird.exe': 'Thunderbird',
  'winword.exe': 'Microsoft Word',
  'excel.exe': 'Microsoft Excel',
  'powerpnt.exe': 'PowerPoint',
  'onenote.exe': 'OneNote',
  'notion.exe': 'Notion',
  'obsidian.exe': 'Obsidian',
  'roamresearch.exe': 'Roam Research',
  'logseq.exe': 'Logseq',
  'todoist.exe': 'Todoist',
  'trello.exe': 'Trello',
  'asana.exe': 'Asana',
  'linear.exe': 'Linear',
  'photoshop.exe': 'Photoshop',
  'illustrator.exe': 'Illustrator',
  'figma.exe': 'Figma',
  'sketch.exe': 'Sketch',
  'xd.exe': 'Adobe XD',
  'afterfx.exe': 'After Effects',
  'premiere.exe': 'Premiere Pro',
  'lightroom.exe': 'Lightroom',
  'gimp-2.10.exe': 'GIMP',
  'blender.exe': 'Blender',
  'spotify.exe': 'Spotify',
  'steam.exe': 'Steam',
  'epicgameslauncher.exe': 'Epic Games',
  'vlc.exe': 'VLC',
  'mpv.exe': 'mpv',
  'explorer.exe': 'File Explorer',
  'cmd.exe': 'Command Prompt',
  'powershell.exe': 'PowerShell',
  'windowsterminal.exe': 'Windows Terminal',
  'taskmgr.exe': 'Task Manager',
  'regedit.exe': 'Registry Editor',
  'notepad.exe': 'Notepad',
  'mspaint.exe': 'Paint',
  'calc.exe': 'Calculator',
  'winrar.exe': 'WinRAR',
  '7zfm.exe': '7-Zip'
}

// Maps exe name (lowercase) to category
const APP_CATEGORY_MAP: Record<string, CategoryName> = {
  'code.exe': 'Development',
  'code - insiders.exe': 'Development',
  'devenv.exe': 'Development',
  'idea64.exe': 'Development',
  'pycharm64.exe': 'Development',
  'webstorm64.exe': 'Development',
  'phpstorm64.exe': 'Development',
  'rider64.exe': 'Development',
  'clion64.exe': 'Development',
  'goland64.exe': 'Development',
  'datagrip64.exe': 'Development',
  'cursor.exe': 'Development',
  'sublime_text.exe': 'Development',
  'notepad++.exe': 'Development',
  'atom.exe': 'Development',
  'vim.exe': 'Development',
  'nvim.exe': 'Development',
  'chrome.exe': 'Browser',
  'firefox.exe': 'Browser',
  'msedge.exe': 'Browser',
  'opera.exe': 'Browser',
  'brave.exe': 'Browser',
  'vivaldi.exe': 'Browser',
  'iexplore.exe': 'Browser',
  'slack.exe': 'Communication',
  'discord.exe': 'Communication',
  'teams.exe': 'Communication',
  'zoom.exe': 'Communication',
  'skype.exe': 'Communication',
  'telegram.exe': 'Communication',
  'whatsapp.exe': 'Communication',
  'signal.exe': 'Communication',
  'mattermost.exe': 'Communication',
  'outlook.exe': 'Communication',
  'thunderbird.exe': 'Communication',
  'winword.exe': 'Productivity',
  'excel.exe': 'Productivity',
  'powerpnt.exe': 'Productivity',
  'onenote.exe': 'Productivity',
  'notion.exe': 'Productivity',
  'obsidian.exe': 'Productivity',
  'todoist.exe': 'Productivity',
  'trello.exe': 'Productivity',
  'asana.exe': 'Productivity',
  'linear.exe': 'Productivity',
  'photoshop.exe': 'Design',
  'illustrator.exe': 'Design',
  'figma.exe': 'Design',
  'sketch.exe': 'Design',
  'xd.exe': 'Design',
  'afterfx.exe': 'Design',
  'premiere.exe': 'Design',
  'lightroom.exe': 'Design',
  'gimp-2.10.exe': 'Design',
  'blender.exe': 'Design',
  'spotify.exe': 'Entertainment',
  'steam.exe': 'Entertainment',
  'epicgameslauncher.exe': 'Entertainment',
  'vlc.exe': 'Entertainment',
  'mpv.exe': 'Entertainment',
  'explorer.exe': 'System',
  'cmd.exe': 'System',
  'powershell.exe': 'System',
  'windowsterminal.exe': 'System',
  'taskmgr.exe': 'System',
  'regedit.exe': 'System',
  'notepad.exe': 'Productivity',
  'calc.exe': 'System'
}

export function getFriendlyName(exeName: string): string {
  const key = exeName.toLowerCase()
  if (APP_NAME_MAP[key]) return APP_NAME_MAP[key]
  // Strip .exe and capitalize
  return exeName.replace(/\.exe$/i, '').replace(/\b\w/g, (c) => c.toUpperCase())
}

export function classifyApp(exeName: string): { category: CategoryName; color: string } {
  const key = exeName.toLowerCase()
  const category: CategoryName = APP_CATEGORY_MAP[key] ?? 'Other'
  const color = CATEGORY_COLORS[category]
  return { category, color }
}

export function getCustomCategory(
  appName: string,
  customCategories: Map<string, { category: string; color: string }>
): { category: string; color: string } | null {
  return customCategories.get(appName) ?? null
}
